workers: 20
gpu: [0]

batch_size: 10
test_batch_size: 4
epoch: 100
lr: 0.005
optimizer: Adam
size: 512
kfold: False
resume: -1
save_results: False
dice_loss: False
encoder: tu-efficientnetv2_s
percent: 100

smoke_test: True
evaluate: False
inpainting: True
update_config: False
optimization: False

eval_metric: None
aug_k: 512
aug_n: 10

resume_wandb: False
